/**
 * TextField Type Definitions
 *
 * Type definitions for the Material Design 3 TextField component.
 * Supports filled and outlined variants with full accessibility via React Aria.
 */

import type {
  LabelHTMLAttributes,
  HTMLAttributes,
  InputHTMLAttributes,
  RefObject,
  ReactNode,
} from "react";
import type { AriaTextFieldProps } from "react-aria";

/**
 * TextField visual variants.
 *
 * - `filled`: Solid background (`surface-container-highest`) with active indicator bottom border.
 * - `outlined`: Transparent with a full rounded border and notched legend for the floating label.
 */
export type TextFieldVariant = "filled" | "outlined";

/**
 * Arguments passed to the TextFieldHeadless render-prop children function.
 *
 * The styled layer uses these to build its custom MD3 DOM while still
 * getting all ARIA props generated by React Aria's useTextField.
 */
export interface TextFieldRenderProps {
  /** Spread onto the <label> element */
  labelProps: LabelHTMLAttributes<HTMLLabelElement>;
  /** Spread onto the <input> or <textarea> element */
  inputProps: InputHTMLAttributes<HTMLInputElement> & HTMLAttributes<HTMLTextAreaElement>;
  /** Spread onto the description helper-text element */
  descriptionProps: HTMLAttributes<HTMLElement>;
  /** Spread onto the error message element */
  errorMessageProps: HTMLAttributes<HTMLElement>;
  /** Whether the field is currently in an invalid state */
  isInvalid: boolean;
  /** Whether the input currently has any focus (keyboard or pointer) */
  isFocused: boolean;
  /** Whether the input has keyboard-visible focus (for focus ring) */
  isFocusVisible: boolean;
  /** Current string value of the field (controlled or uncontrolled) */
  currentValue: string;
  /** Ref forwarded to the underlying input/textarea DOM element */
  inputRef: RefObject<HTMLInputElement | HTMLTextAreaElement>;
}

/**
 * Props for the headless TextField component (Layer 2).
 *
 * Extends React Aria's AriaTextFieldProps for accessibility.
 * Provides behavior without styling.
 */
export interface TextFieldHeadlessProps extends Omit<
  AriaTextFieldProps,
  "children" | "onFocus" | "onBlur"
> {
  /**
   * Label text for the input.
   */
  label?: string;

  /**
   * Helper text displayed below the input.
   * @example "Enter your email address"
   */
  description?: string;

  /**
   * Error message to display when input is invalid.
   * @example "Email is required"
   */
  errorMessage?: string;

  /**
   * Whether the input should expand to fill its container.
   * @default false
   */
  fullWidth?: boolean;

  /**
   * Enable multiline mode (textarea).
   * @default false
   */
  multiline?: boolean;

  /**
   * Number of visible rows for multiline input.
   * @default 3
   */
  rows?: number;

  /**
   * Custom className for the container.
   */
  className?: string;

  /**
   * Custom className for the input element.
   */
  inputClassName?: string;

  /**
   * Custom className for the label element.
   */
  labelClassName?: string;

  /**
   * Custom className for the description element.
   */
  descriptionClassName?: string;

  /**
   * Custom className for the error message element.
   */
  errorClassName?: string;

  /**
   * Handler called when the input is focused.
   */
  onFocus?: (e: React.FocusEvent<HTMLInputElement | HTMLTextAreaElement>) => void;

  /**
   * Handler called when the input loses focus.
   */
  onBlur?: (e: React.FocusEvent<HTMLInputElement | HTMLTextAreaElement>) => void;

  /**
   * Optional render-prop children.
   *
   * When provided as a function, TextFieldHeadless invokes it with all
   * React Aria props and derived state so the styled layer can build its
   * own MD3 DOM without duplicating accessibility wiring.
   *
   * @example
   * ```tsx
   * <TextFieldHeadless label="Email" value={value} onChange={onChange}>
   *   {({ labelProps, inputProps, isFocused }) => (
   *     <div>
   *       <label {...labelProps} className={isFocused ? 'focused' : ''}>Email</label>
   *       <input {...inputProps} className="md3-input" />
   *     </div>
   *   )}
   * </TextFieldHeadless>
   * ```
   */
  children?: ((renderProps: TextFieldRenderProps) => ReactNode) | ReactNode;
}

/**
 * Props for the styled TextField component (Layer 3).
 *
 * Extends TextFieldHeadlessProps with MD3 visual styling options.
 * Strictly follows MD3 spec: single fixed height (56dp), two variants,
 * optional icons, prefix/suffix affixes, and supporting text + counter row.
 */
export interface TextFieldProps extends TextFieldHeadlessProps {
  /**
   * Visual variant of the text field.
   * @default 'filled'
   */
  variant?: TextFieldVariant;

  /**
   * Leading icon rendered at the start of the field.
   * MD3 Specification: icons should be 24×24dp.
   */
  leadingIcon?: ReactNode;

  /**
   * Trailing icon rendered at the end of the field.
   * MD3 Specification: icons should be 24×24dp.
   * Automatically colored `error` when the field is invalid.
   */
  trailingIcon?: ReactNode;

  /**
   * Inline prefix text rendered before the input value.
   * Only visible when the label is in its floating (small) position.
   * Useful for currency symbols, units, etc.
   * @example "$"
   */
  prefix?: ReactNode;

  /**
   * Inline suffix text rendered after the input value.
   * Only visible when the label is in its floating (small) position.
   * Useful for units, domain suffixes, etc.
   * @example "kg"
   */
  suffix?: ReactNode;

  /**
   * Show character counter in the supporting row below the field.
   * Requires `maxLength` to be set.
   * @default false
   */
  characterCount?: boolean;

  /**
   * Maximum number of characters allowed.
   * Enforced on the native input and displayed in the counter when
   * `characterCount` is true.
   */
  maxLength?: number;
}
