import js from "@eslint/js";
import tseslint from "typescript-eslint";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";
import jsxA11y from "eslint-plugin-jsx-a11y";
import storybook from "eslint-plugin-storybook";
import prettier from "eslint-config-prettier";

export default tseslint.config(
  // Ignore patterns
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/build/**",
      "**/.storybook/vitest.setup.ts", // Auto-generated by Storybook
      "**/coverage/**",
      "**/.cache/**",
      "**/pnpm-lock.yaml",
      "eslint.config.js", // Ignore ESLint config itself
    ],
  },

  // Base JavaScript rules
  js.configs.recommended,

  // TypeScript rules
  ...tseslint.configs.recommendedTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: {
          allowDefaultProject: [
            "*.js",
            "*.mjs",
            "packages/react/.storybook/*.ts",
            "packages/tokens/scripts/*.js",
          ],
        },
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },

  // Node.js scripts
  {
    files: ["**/scripts/*.js", "*.config.js", "*.config.mjs"],
    languageOptions: {
      globals: {
        console: "readonly",
        process: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
      },
    },
    rules: {
      "@typescript-eslint/no-floating-promises": "off",
      "@typescript-eslint/explicit-function-return-type": "off",
    },
  },

  // React rules
  {
    files: ["**/*.{ts,tsx}"],
    ...react.configs.flat.recommended,
    ...react.configs.flat["jsx-runtime"],
    settings: {
      react: {
        version: "detect",
      },
    },
    rules: {
      // Disable prop-types (we use TypeScript)
      "react/prop-types": "off",

      // Enforce self-closing for components without children
      "react/self-closing-comp": "error",

      // Prevent missing React import (not needed in React 18+ with new JSX transform)
      "react/react-in-jsx-scope": "off",

      // Enforce button type attribute
      "react/button-has-type": "error",

      // Warn on direct mutation of state
      "react/no-direct-mutation-state": "error",

      // Enforce fragments shorthand
      "react/jsx-fragments": ["error", "syntax"],

      // Disallow target="_blank" without rel="noopener noreferrer"
      "react/jsx-no-target-blank": "error",
    },
  },

  // React Hooks rules
  {
    files: ["**/*.{ts,tsx}"],
    plugins: {
      "react-hooks": reactHooks,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      // Enforce Rules of Hooks
      "react-hooks/rules-of-hooks": "error",
      // Enforce exhaustive deps
      "react-hooks/exhaustive-deps": "warn",
    },
  },

  // Accessibility rules (jsx-a11y)
  {
    files: ["**/*.{ts,tsx}"],
    ...jsxA11y.flatConfigs.recommended,
    rules: {
      // Enforce alt text on images
      "jsx-a11y/alt-text": "error",

      // Enforce ARIA props are valid
      "jsx-a11y/aria-props": "error",
      "jsx-a11y/aria-proptypes": "error",
      "jsx-a11y/aria-unsupported-elements": "error",

      // Enforce role attribute is valid
      "jsx-a11y/role-has-required-aria-props": "error",
      "jsx-a11y/role-supports-aria-props": "error",

      // Enforce tabIndex value is not > 0
      "jsx-a11y/tabindex-no-positive": "error",

      // Enforce heading hierarchy
      "jsx-a11y/heading-has-content": "error",

      // Enforce interactive elements are keyboard accessible
      "jsx-a11y/interactive-supports-focus": "error",

      // Warn on click handlers without keyboard handlers (React Aria handles this)
      "jsx-a11y/click-events-have-key-events": "warn",
      "jsx-a11y/no-static-element-interactions": "warn",
    },
  },

  // Storybook rules
  {
    files: ["**/*.stories.{ts,tsx}"],
    plugins: {
      storybook,
    },
    rules: {
      ...storybook.configs.recommended.rules,
    },
  },

  // TypeScript-specific overrides
  {
    files: ["**/*.{ts,tsx}"],
    rules: {
      // Enforce consistent type imports
      "@typescript-eslint/consistent-type-imports": [
        "error",
        {
          prefer: "type-imports",
          fixStyle: "separate-type-imports",
        },
      ],

      // Warn on unused variables
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
        },
      ],

      // Allow empty interfaces (useful for extending)
      "@typescript-eslint/no-empty-interface": "off",

      // Enforce naming conventions
      "@typescript-eslint/naming-convention": [
        "error",
        {
          selector: "typeParameter",
          format: ["PascalCase"],
          prefix: ["T"],
        },
      ],

      // Disallow explicit any
      "@typescript-eslint/no-explicit-any": "error",

      // Enforce consistent array type syntax
      "@typescript-eslint/array-type": ["error", { default: "array-simple" }],

      // Require return types on functions
      "@typescript-eslint/explicit-function-return-type": [
        "warn",
        {
          allowExpressions: true,
          allowTypedFunctionExpressions: true,
        },
      ],
    },
  },

  // Test files
  {
    files: [
      "**/*.test.{ts,tsx}",
      "**/*.spec.{ts,tsx}",
      "**/test/**/*.{ts,tsx}",
      "**/test/**/*.ts",
    ],
    rules: {
      // Allow non-null assertions in tests
      "@typescript-eslint/no-non-null-assertion": "off",

      // Allow any in tests for mocking
      "@typescript-eslint/no-explicit-any": "off",

      // Allow empty functions in tests (mocks)
      "@typescript-eslint/no-empty-function": "off",

      // Don't require return types in tests
      "@typescript-eslint/explicit-function-return-type": "off",

      // Don't require button type in tests (testing raw elements)
      "react/button-has-type": "off",
    },
  },

  // Disable rules that conflict with Prettier
  prettier
);
