#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run lint-staged (will be configured in Task 9.5)
# For now, this is a placeholder that will be updated
echo "🪝 Running pre-commit checks..."

# This will be replaced with: pnpm lint-staged
# Once we set up lint-staged in Task 9.5
